### ISSUE TITLE
Possible incompatibility with Tableau 2021.4.2

### ISSUE THREAD

**Issue by DaryaRudych** [TheInformationLab/Tableau-Extension-ExportAll#112]
In the new version of Tableau Server 2021.4.2 , when there is an extension on the sheet, the tooltips do not show any data upon initial page load.

**Comment by mac471** [comment]
There is this post on the Tableau Community forum that describes this problem along with a sample workbook: [Tooltips do not display on Tableau Online dashboards that use dashboard extensions](https://community.tableau.com/s/question/0D74T000002gQtBSAU/detail?s1oid=00D4T000000Dj8G&t=1646839754447&s1nid=0DB4T000000GnPK&emkind=chatterCommentNotification&s1uid=0054T000001O4VZ&emtm=1646817899408&fromEmail=1&s1ext=0).  This _appears_ to be an issue with Tableau Online as the problem can also be reproduced with a Tableau-provided dashboard extension (Single Checkbox Parameters).  Hoping that Tableau takes ownership for looking into this Online problem.

**Comment by johnDance** [comment]
@DaryaRudych & @mac471 
The Tableau Extensions team has found and fixed the issue. It will be fixed in the March maintenance release of 2021.4, and in online in a week or two.
Thank you!
John

**Comment by johnDance** [comment]
If you have general extension issues, or feel it might be a general extension issue, feel free to post on https://github.com/tableau/extensions-api/issues, we review those issues regularly. 
Thanks again,
John

**Comment by mac471** [comment]
@johnDance, thanks for getting this fixed!  Much appreciated!
