### ISSUE TITLE
Use Excel picture/image for button instead or in addition to button label

### ISSUE THREAD

**Issue by Aya-Abdelwahab** [TheInformationLab/Tableau-Extension-ExportAll#115]
@craigbloodworth 
Is it possible to have an option of showing an excel download image/pic?
May have both button image &/or button label to choose one or both...

**Comment by andre347** [comment]
This is not something on the roadmap for this extension but we are open for PRs. You can also add this functionality yourself and self-host the extension on your own webserver.
