### ISSUE TITLE
User Prompts Display Even When Set to Hidden

### ISSUE THREAD

**Issue by JBatulevitz** [TheInformationLab/Tableau-Extension-ExportAll#17]
Hello,

We are trying to develop a map that allows users to view and download the locations where they can receive physical and mental health services.  We are using Tableau Server (version 2018.3.2) and have added the Source URL from the Export All .trex file to our server settings and set User Prompts to "hide" to prevent users from getting the Allow Extension popup window.

![image](https://user-images.githubusercontent.com/51452724/66836948-39480280-ef30-11e9-8be3-a4aa2f4ae8f8.png)

Unfortunately, after enabling the extension and trying to hide user prompts, we still get the Allow Extension popup window.

![image](https://user-images.githubusercontent.com/51452724/66837167-8af08d00-ef30-11e9-8305-76558cc65123.png)

We are following the same process with other extensions and are not receiving the popup window when users load the visualization.  Are we missing any other steps to enable this extension without our users getting the popup prompt?

Thank You.

**Comment by andre347** [comment]
Hi @JBatulevitz 

Does this 'Allow Extension' window pop up on Tableau Server when they visit a dashboard that contains this extension or are you seeing this in Tableau Desktop? You don't have control over the latter because the window will always pop up on Tableau Desktop, but on server it should be disabled when you switched that setting.

**Comment by JBatulevitz** [comment]
Hello,

Thank you for your reply.  We are seeing this 'Allow Extension' window pop
up while users are viewing a dashboard posted to our Tableau Server
(currently version 2018.3.2) even though we have the setting to hide user
prompts.  The prompt seems to appear regardless of the browser the viewer
is using (Internet Explorer, Edge, Chrome, FireFox, etc.).  We have other
extensions which have user prompts hidden and those don't seem to appear on
Tableau Server.  For some reason, we only continue to get the prompts for
this extension.  Are any other users having this difficulty or is there
another workaround that we can consider?

Thank you and have a great day.

**Comment by craigbloodworth** [comment]
Hi @JBatulevitz 

Technically the URL doesn't need the html page on the end of it and is simply https://exportallextension.theinformationlab.io

If you do use the html page a redirect takes you to the clean URL. Could you try adding just https://exportallextension.theinformationlab.io to your list of allowed extension URLs and see if that solves it?

Craig

**Comment by JBatulevitz** [comment]
Hi Craig,

Thank you for your feedback.  I will try this adjustment later today and
then follow up with you once we have tested this.  We appreciate your time
and help with this.

Have a great day,
Jeff
