### ISSUE TITLE
Problems running on IE11

### ISSUE THREAD

**Issue by bhamill** [TheInformationLab/Tableau-Extension-ExportAll#2]
Hi, We're trying to add the Export extension to our workbooks and having some problems viewing those workbooks in IE11. We've been able to get around some javascript syntax that's not supported on IE11 (lambda functions, template literals), but now we're getting an "Access is denied" error deep within the xlsx library. Do you have any experience running the extension on IE11 and is IE11 in the plans? Thanks.

**Comment by andy-lb** [comment]
We are also experiencing the same issue a work around would be appreciated.

**Comment by craigbloodworth** [comment]
IE11 support has now been added with the v2 release however a [bug with the extension SDK](https://github.com/tableau/extensions-api/issues/215) is preventing the extension being configured directly in the browser. As a work around please configure first in Desktop and then publish the workbook.

Excel files will now at least download in IE11.

**Comment by DataPalla** [comment]
@craigbloodworth  I am unable download data for the second time when I click the button in IE11, it throws following error (Deferred exception: Permission denied undefined undefined)and IE crashes,I am using Trusted auth to authenticate users, when IE is reloading it is using same expired ticket to reload and View is not loading.
can you please help ? 
Thanking you in anticipation - Sai Sandeep
