### ISSUE TITLE
Inquiry on Extension

### ISSUE THREAD

**Issue by kedohert** [TheInformationLab/Tableau-Extension-ExportAll#27]
I am a Tableau Admin and have a customer looking to enable this extension on the Server.. is this Extension able to function via the Server UI?

A few other questions:

1) For the extension to function does it have to go out to an external address? I see in the manifest file it is referencing the Information Lab URL so wanted to verify?
2) Does Full Data or Summary Data need to be enabled for this extension on Server?

**Comment by andre347** [comment]
1. The external address you see in the trex file is where this extension is hosted by us. This doesn't mea data from your dashboard goes to this location. What I do want to stress is that this is using an external library for generating the XLSX file. If you want full control over this extension I would recommend cloning it and hosting it on your own servers. 
2. This extension only gets Summary data and never grabs the underlying data. So you don't have to turn on full data export.
