### ISSUE TITLE
Save to File from tableau desktop

### ISSUE THREAD

**Issue by shimrot** [TheInformationLab/Tableau-Extension-ExportAll#3]
I have need to be able to save the excel export results from a tableau "desktop" instance.  We have no server instance which is able to run these extensions.  Even if we did, there are other restrictions which can make it pretty inconvenient.  

Nevertheless, we have a need (requirement really) to supply excel results with workbooks.  We have discussed switching away from tableau for this specific reason. But, since there is an investment in tableau, I've been looking for alternatives.   This ExportData extension seems to be 95% there, but I ran into some issues:  
1. Could only get file results from a server instance.
2. The resulting file only produced strings, and on conversion would crash Excel.

After a lot of debug and code digging, I figured out the 2nd issue - hence the proposed "Col_Types" branch changes (https://github.com/shimrot/Tableau-Extension-ExportData/tree/Col_Types).

For the 1st issue, I was able to opening an external window via javascript Window.Open call.  Then tried 3 different cross window messaging methods to transfer data between windows (postMessage/onmessage, BroadcastChannel, and a 3rd which escapes me now...) .  Was not able to get any to work for varied reasons.  Since I needed to show something, I punted and added some ajax calls to a local server I own, to squirrel away the generated excel data blob, and then have the new window able to download.  

My end solution in the "indirect_server_save" (https://github.com/shimrot/Tableau-Extension-ExportData/tree/indirect_server_save) branch is not generalized enough for anyone else to use directly (because of the extra https server requirement).  However, I hope someone else can think of some way to transfer between windows, or maybe can think of other alternatives.

Thanks
Kris

**Comment by craigbloodworth** [comment]
Thanks so much for your feedback. I too would like Tableau to enable downloads in extensions and would prefer to push this request rather than opening the can of worms that is allowing folks to send their data to a third party server for processing and download.

Good news is the extension now encourages users to email the Tableau PM to request that downloads be enabled. Hopefully that will do the trick.

**Comment by Bricebr** [comment]
Here, the extension is not allowed to show anything under Tableau Desktop, the frame remains blank. Only the "about" can popup. It should be sand-boxed with some bootstrap stuff to avoid any external url. Don't know If it can be done straitghtforward from the npm install start, using the source, or if it needs the build step ? Any Advice ?

**Comment by craigbloodworth** [comment]
Great news folks. The extension now works as expected in Tableau Desktop 2019.4! In order for the Excel file to export you'll need to update Desktop to at least version 2019.4
