### ISSUE TITLE
New fields not available

### ISSUE THREAD

**Issue by leefinar** [TheInformationLab/Tableau-Extension-ExportAll#31]
Add the extension to the dashboard and configure it.  When new fields are added to the targeted sheet(s), they do not appear in the configuration of the extension.  Furthermore, if I add a new sheet to the dashboard and try to configure the extension to target the new sheet, the new sheet doesn't show up.  If I remove the extension from the dashboard and add it back, the same problems exist.  And the Reset button doesn't seem to cure the problems.

**Comment by craigbloodworth** [comment]
The latest version [2.2.0](https://github.com/TheInformationLab/Tableau-Extension-ExportAll/releases/tag/v2.2.0) does a better job of handling changing meta data after the extension has been configured.
