### ISSUE TITLE
Question: Internal Use of ExportAll Extension

### ISSUE THREAD

**Issue by jschuhdodge** [TheInformationLab/Tableau-Extension-ExportAll#37]
This is more a question than an issue for @craigbloodworth.  We would like to use this extension, however, we have some security needs that would likely require us to run this extension on our internally hosted server vs. using the extension as it is available.  Are we ok to download a copy of this code here and stand this extension up internally on our own servers where it would be allowed to work in our intranet and not move outside our firewalls?

**Comment by jpatel-uillinois** [comment]
I'm too looking forward for this issue.

Thank you,
Jay

**Comment by dshmuryev** [comment]
I'm too looking forward for this issue.
We need to host the extension code on the local server and would be great to have step-by-step instruction for deploying

Thanks!

**Comment by ericknizard** [comment]
we too are interested in a local version of this extension

**Comment by craigbloodworth** [comment]
I've just updated the build and deployed a release which can be downloaded and added to an internal web server [Release 2.1.1](https://github.com/TheInformationLab/Tableau-Extension-ExportAll/releases/tag/2.1.1) There is no requirement for this web server, all the code is browser based Javascript (no PHP, ASP, etc).
