### ISSUE TITLE
Aliases in Export File

### ISSUE THREAD

**Issue by jnhallam** [TheInformationLab/Tableau-Extension-ExportAll#4]
The export file currently labels fields with Tableau's notation for SUM(FieldName), ATTR(FieldName), AGG(FieldName), etc. Are there plans to support aliases/the ability to rename columns in the exported file?

**Comment by psuanm5030** [comment]
This would be a great feature!

**Comment by craigbloodworth** [comment]
This feature has now been implemented in the latest version (v2) of the extension.

Thanks for the feedback and enjoy!

**Comment by jnhallam** [comment]
Thanks Craig, looking forward to using the new version.
