### ISSUE TITLE
Extension no longer working in Tableau Desktop 2020.2

### ISSUE THREAD

**Issue by melanatech** [TheInformationLab/Tableau-Extension-ExportAll#45]
I started a dashboard while working in Tableau 2019.4 and the extension worked fine. When I upgraded the software I could no longer edit the existing configuration nor start over by adding a new button. Any guidance on getting this to work would be awesome. It is just a greyed out button and the configuration screen is empty anytime I try to add it.

<img width="779" alt="Screen Shot 2020-06-17 at 1 19 14 PM" src="https://user-images.githubusercontent.com/20934522/84928919-24aea200-b09d-11ea-9f00-fc9911eafb68.png">

**Comment by Jorsyn** [comment]
I am having the same issue.

**Comment by melanatech** [comment]
Right now, the only workaround is to 

- create a new temporary dashboard from scratch with the sheets you need and add the extension with the name changes you need
- change the .twb to .xml
- find and copy the <instance settings></instance settings> from the new temporary dashboard into the old dashboard
- save and change the .xml back to .twb
- open the .twb and delete the temporary dashboard

If you have no design on your dashboard and you're just dragging and dropping into fixed tiles, this isn't really an issue. It would be nice to not have to do restart a custom designed dashboard from scratch just to update the export, especially since not all team members feel comfortable going into the xml.

**Comment by craigbloodworth** [comment]
Extension has now been upgraded and tested with versions 2018.2 & 2020.2 (release [2.2.0](https://github.com/TheInformationLab/Tableau-Extension-ExportAll/releases/tag/v2.2.0)
