### ISSUE TITLE
Export All extention limit 10,000 records

### ISSUE THREAD

**Issue by katiehab** [TheInformationLab/Tableau-Extension-ExportAll#50]
There appears to be a 10,000 record limit for the Export All extension.  Is there a setting so the Tableau workbook developer or server admin can make changes to this exort record limilt setting?

**Comment by katiehab** [comment]
This limit is when the user uses the Export buttun in a published workbook dashboard from Tableau server via the web.  The extensiion url is enabled and Full Data Access is set to Allow on the Extensions settings tab for the Export All extension.

**Comment by craigbloodworth** [comment]
This is a [known issue](https://github.com/tableau/extensions-api/issues/334) with Tableau 2020.2 up to 2020.2.3 (reported) and also affected the 'View Data' function native to Tableau. I have tested with 2020.2.4 and can confirm that the 10k record restriction has been removed.
