### ISSUE TITLE
Unable to get the button to display

### ISSUE THREAD

**Issue by ericknizard** [TheInformationLab/Tableau-Extension-ExportAll#54]
we have the extension pointing to our internal Tableau Server (replacing 'https://exportallextension.theinformationlab.io' by our server URL in the ExportAll.trex file) but instead of displaying the Export button, it launches our tableau server url ... any idea on how to configure it so that we can add the button?

Any help is truly appreciated

**Comment by andre347** [comment]
Correct. In the trex file you specify the URL of where the Extension is hosted. Not your Tableau Server URL. If you want the button to show up (and use the extension) you can leave it to the original URL that was in the trex file. This is at a location that is hosted by The Information Lab.

**Comment by ericknizard** [comment]
thanks Andre, do you have the steps detailing how we can properly install it on our server? not sure it's clear to us on where do get that URL where the extension is hosted. thanks a ton !

**Comment by andre347** [comment]
You can use the trex that you've downloaded in dashboards. This can be in desktop and server / online. Then you can whitelist the URL of the extension in the server settings. Go to Settings > Extensions > Add this URL: https://exportallextension.theinformationlab.io/exportall.html

You don't install extensions on your Tableau Server.
