### ISSUE TITLE
Feature Request: Ability to Lock into a Version of the extensions 

### ISSUE THREAD

**Issue by HSJD19** [TheInformationLab/Tableau-Extension-ExportAll#64]
Based on my regulatory requirements , it would be really nice to be able to have a stable version and only upgrade when I chose. 
For example, if I test and validate my dashboards with v2.2 , I would like for no changes to be made to that version and that changes or updates made to new versions would not effect the version. 
At present it seems that anytime new code is pushed , all extensions get updated no matter what version was originally downloaded.

**Comment by HSJD19** [comment]
@craigbloodworth directions on a internal deployment would be awesome .

**Comment by ericknizard** [comment]
+1 on getting clear instructions on how to deploy into internal server ... we have been unable to deploy it internally for a while !
