### ISSUE TITLE
Detailed instructions/guidelines on how to deploy the extension on-prem

### ISSUE THREAD

**Issue by ericknizard** [TheInformationLab/Tableau-Extension-ExportAll#68]
when could we expect to get detailed instructions on how to deploy the extension on our internal infrastructure.

we would really like to use it but have been unsuccessful in trying to implement it thus far.

Any help will be highly appreciated

**Comment by ericknizard** [comment]
any update on when this will be made available ??

**Comment by craigbloodworth** [comment]
The repository README has been updated with instructions for installing the extension on a local web server

**Comment by ericknizard** [comment]
Followed the steps but the button still doesn’t appear … any idea ☹?

[cid:image001.png@01D6F574.BF7D4E00]
