### ISSUE TITLE
No license specified on the project

### ISSUE THREAD

**Issue by aormerod-gs** [TheInformationLab/Tableau-Extension-ExportAll#71]
Are you able to confirm / define the license for this project?  I see the comment on #61 that says it's intended to be modifiable, but for our usage unfortunately we need a specific license identified.

There seems to be a pull request (https://github.com/TheInformationLab/Tableau-Extension-ExportAll/pull/67) to define it as MIT.  Is that the license being used?

Thanks,

**Comment by craigbloodworth** [comment]
The GNU license was added with [this commit](https://github.com/TheInformationLab/Tableau-Extension-ExportAll/commit/e661fc93e424ac093b133f91ece18ab62146ff0e)

**Comment by aormerod-gs** [comment]
Thanks for stating a license, certainly should help people having that.

Is there a particular driver for choosing GPLv3 rather than MIT?  (Within some organizations, by policy, use of GPL is more restricted / harder than MIT).

Thanks
