### ISSUE TITLE
More of a question, and not an issue

### ISSUE THREAD

**Issue by hpunjabi** [TheInformationLab/Tableau-Extension-ExportAll#81]
I apologize in advance for lack of my knowledge, but I decided to ask this question here as couldn't find any relevant information on the web. The Tableau extension, Export All, is it free? or is Tableau going to charge you for the extension that you download in your monthly user fee?

**Comment by andre347** [comment]
No worries! Thanks for raising. This Extension is free for you to use. There are no additional charges or fees for using it.
